name: Auto update dependencies

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  auto-update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v2
      with:
        persist-credentials: false 
        
    - name: Install Linux requirements
      run: |
        apt_dependencies="git curl libssl-dev pkg-config libudev-dev libv4l-dev"
        echo "Run apt update and apt install the following dependencies: $apt_dependencies"
        sudo apt update
        sudo apt install -y $apt_dependencies
    
    - name: Run auto dependency update
      uses: romoh/dependencies-autoupdate@main
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        update-command: "'cargo update && cargo test'"
        